### ISSUE TITLE
WebAC properties in bad namespace

### ISSUE THREAD

**Issue by mirekys** [CESNET/fedoralink#4]
with model annotated as:
@fedora(namespace=ACL, rdf_types=(ACL.Authorization,))
class Authorization(Model):

Migration results in properties ending in wrong CESNET namespace:

 cesnet: agent
    urn:admin 
cesnet: mode
    http://www.w3.org/ns/auth/acl#Read 
    http://www.w3.org/ns/auth/acl#Write 
fedora: created
    2017-08-28T14:30:51.321Z 
fedora: createdBy
    fedoraAdmin 
fedora: hasParent
    http://localhost:8080/fcrepo/rest/web_acl_authorization 
fedora: hasVersions
    http://localhost:8080/fcrepo/rest/web_acl_authorization/2f/e0/45/d8/2fe045d8-b561-4d90-b36a-bd55b5f7a261/fcr:versions 
fedora: lastModified
    2017-08-28T14:30:51.321Z 
fedora: lastModifiedBy
    fedoraAdmin 
fedora: writable
    true

**Comment by mesemus** [comment]
@mirekys Seems to be working - see fedoralink/tests/test_differentnamespace.py . Can you remove the migrations and try again? If there are issues, please add a failing test to the teststuite. Thanks.

**Comment by mirekys** [comment]
@mesemus  It works when `rdf_name` and `rdf_attributes` are set on `FedoraField` explicitly.
But it looks like it doesn't implicitly inherit these attributes from a containing class, if nothing is being set on FedoraField.
