### ISSUE TITLE
ElasticSearch object mapping of JSONField doesn't work

### ISSUE THREAD

**Issue by mirekys** [CESNET/fedoralink#8]
When creating index on JSONField with assigned JSON value, the following ES error occurs:
`
  elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'object mapping for [http_3a_2f_2fcesnet_2ecz_2fns_2frepository_23model_5ffields] tried to parse field [http_3a_2f_2fcesnet_2ecz_2fns_2frepository_23model_5ffields] as object, but found a concrete value')
`

**Comment by mesemus** [comment]
Fixed too long json in cd9fa3889dd636b6211e12ef241ba89ed73ff7c2
@mirekys : Please add example of the "concrete" value problem to test_json

**Comment by mirekys** [comment]
Thanks, works as expected & tests passes. Closing the issue
